version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: passward
      MYSQL_DATABASE: db
      MYSQL_USER: comwith
      MYSQL_PASSWORD: rootpassward
    ports:
      - "3306:3306"
    networks:
      - flask-network
    volumes:
      - mysql-data:/var/lib/mysql

  flask:
    build: .
    container_name: flask-app
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=comwith
      - MYSQL_PASSWORD=passward
      - MYSQL_DB=db
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
