"""Auto migration

Revision ID: 076adcde5553
Revises: 
Create Date: 2025-01-17 04:44:50.544567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076adcde5553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('musicsheets',
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('pdf_url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('composer', sa.String(length=20), nullable=False),
    sa.Column('instruments', sa.String(length=20), nullable=False),
    sa.Column('stages', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('sheet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('musicsheets')
    op.drop_table('users')
    # ### end Alembic commands ###
