"""Initial migration

Revision ID: 18fd04100e6a
Revises: 
Create Date: 2025-01-27 15:20:12.271256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18fd04100e6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('musicsheets',
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('pdf_url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('composer', sa.String(length=20), nullable=False),
    sa.Column('instruments', sa.String(length=20), nullable=False),
    sa.Column('stages', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('sheet_id')
    )
    op.create_table('video',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('video_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sheet_id'], ['musicsheets.sheet_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('musicsheets')
    op.drop_table('users')
    # ### end Alembic commands ###
